<a href="https://colab.research.google.com/github/karunyajayaraman/India-Port-Level-Export-Analytics/blob/main/India_Port_Level_Export_Analytics_2018_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **India Port Level Export Analytics-(2018-2024)**

# **Dataset information**
Source : India Data Portal/Directorate General of Commercial Intelligence and Statistics (DGCI&S)

Location : India

Year/Timeline : 2018-2024

Domain: Commerce / International Trade / Exports

Dataset Name: Exports at Principal Commodity Level

# **Objective**

1. Analyze the overall export performance of India across the available years
based on export value and quantity.
2. Identify the top-performing principal commodities based on their contribution to total export value.
3. Analyze state-wise export performance and identify the major exporting states.
4. Examine yearly export trends to identify growth, decline, and changes in export performance over time.
5. Analyze the relationship between commodities and states to identify which commodities contribute significantly to exports from different states.
6. Identify major changes in commodity-wise export performance across different years.
7. Measure the contribution and concentration of major commodities and states in India's overall exports.
8. Generate business-oriented insights and recommendations based on commodity, state, and year-wise export patterns

In [24]:
#Import the neccesary Libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt

#Dataset Access

*   The original dataset is **100 MB**, which exceeds **GitHub’s 25 MB** browser upload limit.
*  Therefore, the complete dataset is stored in **Google Drive** without splitting or modifying it.
*   **Google Drive is mounted in Google Colab** to access the dataset directly for the capstone project.
*   This approach preserves **data integrity** and allows the complete dataset to be used for analysis and preprocessing.

In [25]:
#Mounting the Drive to colab notebook
from google.colab import drive
drive.mount('/content/drive')

#Read a CSV file from Drive
df = pd.read_csv("/content/drive/MyDrive/Data Analytics /Capstone Project - Exports at Principal Commodity Level /exports-at-principal-commodity-level.csv")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [45]:
#Displaying the Dataframe
df

,id,date,state_name,state_code,country,port,pc_code,commodity,units,quantity,dollars_value,inr_value
0,0,2018-01-01,Andhra Pradesh,28,Albania,Krishnapatnam,F3,"Granit, Natrl Stone And Prodct",Kgs,82500,27451,1746880
1,1,2018-01-01,Andhra Pradesh,28,Albania,Visakhapatnam Sea,L5,"Aluminium, Products Of Aluminm",Ton,504,1185847,75463619
2,2,2018-01-01,Andhra Pradesh,28,Algeria,Apiic Building Product,F3,"Granit, Natrl Stone And Prodct",Kgs,1182000,620666,39497231
3,3,2018-01-01,Andhra Pradesh,28,Algeria,Krishnapatnam,F3,"Granit, Natrl Stone And Prodct",Kgs,1782340,759041,48303027
4,4,2018-01-01,Andhra Pradesh,28,Algeria,Visakhapatnam Sea,J5,Ceramics And Allied Products,NaN,0,153958,9797426
...,...,...,...,...,...,...,...,...,...,...,...,...
6912487,6912487,2023-12-01,West Bengal,19,Zambia,Kolkata Sea,O3,Pumps Of All Types,NaN,0,1378,114727
6912488,6912488,2023-12-01,West Bengal,19,Zimbabwe,Kolkata Air,N6,Indl. Machnry For Dairy Etc,NaN,0,14459,1204125
6912489,6912489,2023-12-01,West Bengal,19,Zimbabwe,Kolkata Sea,R7,Jute Hessian,NaN,0,106177,8842324
6912490,6912490,2023-12-01,West Bengal,19,Zimbabwe,Kolkata Sea,R9,Other Jute Manufactures,NaN,0,36419,3032951
6912491,6912491,2023-12-01,West Bengal,19,Zimbabwe,Kolkata Sea,K9,"Plastc Sht, Film, Plts Etc",Kgs,117351,165573,13788697

In [27]:
#Create a copy for original Dataframe
df_safe = df.copy()

# Initial Inspect

In [47]:
#Initial EDA
# Display first 5 rows
print('First 5 Rows\n')
df.head()

First 5 Rows

,id,date,state_name,state_code,country,port,pc_code,commodity,units,quantity,dollars_value,inr_value
0,0,2018-01-01,Andhra Pradesh,28,Albania,Krishnapatnam,F3,"Granit, Natrl Stone And Prodct",Kgs,82500,27451,1746880
1,1,2018-01-01,Andhra Pradesh,28,Albania,Visakhapatnam Sea,L5,"Aluminium, Products Of Aluminm",Ton,504,1185847,75463619
2,2,2018-01-01,Andhra Pradesh,28,Algeria,Apiic Building Product,F3,"Granit, Natrl Stone And Prodct",Kgs,1182000,620666,39497231
3,3,2018-01-01,Andhra Pradesh,28,Algeria,Krishnapatnam,F3,"Granit, Natrl Stone And Prodct",Kgs,1782340,759041,48303027
4,4,2018-01-01,Andhra Pradesh,28,Algeria,Visakhapatnam Sea,J5,Ceramics And Allied Products,NaN,0,153958,9797426

In [48]:
#Display Random Data
print('Random 15 Rows\n')
df.sample(15)

Random 15 Rows

,id,date,state_name,state_code,country,port,pc_code,commodity,units,quantity,dollars_value,inr_value
5884865,5884865,2018-11-01,Maharashtra,27,Canada,Icd Tumb,K9,"Plastc Sht, Film, Plts Etc",Kgs,18846,37491,2693883
3042606,3042606,2018-06-01,Maharashtra,27,Ireland,Nhava Sheva Sea,N7,"Atm, Injctng Mlding Mchnry Etc",NaN,0,4564,309439
870770,870770,2021-02-01,Gujarat,24,Sierra Leone,"Hazira Port, Surat",J9,"Paper, Paper Board And Product",NaN,0,21419,1558339
347935,347935,2022-01-01,Gujarat,24,Congo D. Rep.,Ahmedabad Air Cargo Complex,M4,Electrodes,Kgs,48,1738,129377
3306093,3306093,2021-06-01,Punjab,3,Australia,Acc Amritsar (Rajasansi),N7,"Atm, Injctng Mlding Mchnry Etc",Kgs,1,10,730
508294,508294,2024-01-01,Andhra Pradesh,28,Panama Republic,Brandix Indiaapparel Pvt Ltd,Q6,Rmg Cotton Incl Accessories,NaN,0,187371,15574505
2693871,2693871,2021-05-01,Punjab,3,Russia,Icd Chowpayal,I5,Cosmetics And Toiletries,Kgs,3926,42144,3087794
3188365,3188365,2020-06-01,Gujarat,24,Saudi Arab,Mundra,Q8,Rmg Manmade Fibres,NaN,0,10532,797562
2163050,2163050,2022-04-01,Karnataka,29,Japan,Icd Bangalore,H4,Ayush And Herbal Products,Kgs,83,336,25612
6340455,6340455,2023-11-01,Rajasthan,8,Switzerland,Mahindra World City (Jaipur),K1,Plywood And Allied Products,NaN,0,20803,1732863
6035425,6035425,2020-11-01,Gujarat,24,Mexico,Mundra,B1,Spices,Kgs,210000,335466,24898196
4674180,4674180,2022-08-01,Uttar Pradesh,9,Nepal,Nautanwa (Sonauli),P6,Manmade Staple Fibre,Kgs,1660778,1905322,151577896
107634,107634,2019-01-01,Karnataka,29,Russia,Bangalore Airport,O1,Other Misc. Engineering Items,NaN,0,17791,1258419
5809076,5809076,2023-10-01,Maharashtra,27,South Africa,Concor Icd/Mmlp Khapri Nagpur,P3,Electronics Instruments,NaN,0,3510,292130
3264349,3264349,2021-06-01,Gujarat,24,Finland,Mundra,K1,Plywood And Allied Products,NaN,0,103970,7647844

In [53]:
#shape of the DataFrame(Rows * Columns)
print(f'Rows * Columns : {df.shape}')
#df.shape

Rows * Columns : (6912492, 12)

In [60]:
#Column name of DataFrame(Index)
print(f'Column Names\n\n{df.columns}')
#df.columns

Column Names

Index(['id', 'date', 'state_name', 'state_code', 'country', 'port', 'pc_code',
       'commodity', 'units', 'quantity', 'dollars_value', 'inr_value'],
      dtype='object')

In [61]:
#check the Structure and datatypes
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6912492 entries, 0 to 6912491
Data columns (total 12 columns):
 #   Column         Dtype
---  ------         -----
 0   id             object
 1   date           datetime64[ns]
 2   state_name     object
 3   state_code     object
 4   country        object
 5   port           object
 6   pc_code        object
 7   commodity      object
 8   units          object
 9   quantity       int64
 10  dollars_value  int64
 11  inr_value      int64
dtypes: datetime64[ns](1), int64(3), object(8)
memory usage: 632.9+ MB

Data Quality Check

In [63]:
#check the null Availability
print('Check the Missing values in each column')
df.isnull().sum()

Check the Missing values in each column

id                     0
date                   0
state_name             0
state_code             0
country                0
port                   0
pc_code                0
commodity              0
units            4468611
quantity               0
dollars_value          0
inr_value              0
dtype: int64

In [65]:
#check the duplicates
print(f'Number of duplicate Rows : {df.duplicated().sum()}')
#df.duplicated().sum()

Number of duplicate Rows : 0

In [67]:
#check the Dtypes
print("Data Types of Each Column")
df.dtypes

Data Types of Each Column

id                       object
date             datetime64[ns]
state_name               object
state_code               object
country                  object
port                     object
pc_code                  object
commodity                object
units                    object
quantity                  int64
dollars_value             int64
inr_value                 int64
dtype: object

As per above, Initial First EDA, id,date,state_code to be changed to str & datetime Dtype

In [36]:
#ID Column should be STRING - Convert Dtype int64 to str
df['id'] = df['id'].astype(str)

In [37]:
#convert date Dtype as datetime using pd.to_datetime
df['date'] = pd.to_datetime(df['date'])

In [41]:
#Convert state_code Dtype as str
df['state_code'] = df['state_code'].astype(str)

In [68]:
# check the Dtype changed
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6912492 entries, 0 to 6912491
Data columns (total 12 columns):
 #   Column         Dtype
---  ------         -----
 0   id             object
 1   date           datetime64[ns]
 2   state_name     object
 3   state_code     object
 4   country        object
 5   port           object
 6   pc_code        object
 7   commodity      object
 8   units          object
 9   quantity       int64
 10  dollars_value  int64
 11  inr_value      int64
dtypes: datetime64[ns](1), int64(3), object(8)
memory usage: 632.9+ MB

In [69]:
#Show summary statistics for numeric columns
df.describe()

,date,quantity,dollars_value,inr_value
count,6912492,6.912492e+06,6.912492e+06,6.912492e+06
mean,2021-05-02 16:10:48.178863872,6.441445e+04,3.579661e+05,2.724225e+07
min,2018-01-01 00:00:00,0.000000e+00,0.000000e+00,1.000000e+00
25%,2019-09-01 00:00:00,0.000000e+00,2.153000e+03,1.622700e+05
50%,2021-06-01 00:00:00,0.000000e+00,1.950200e+04,1.466100e+06
75%,2023-01-01 00:00:00,3.900000e+01,9.976200e+04,7.535096e+06
max,2024-07-01 00:00:00,7.620654e+09,1.449331e+09,1.192634e+11
std,NaN,3.720349e+06,5.306167e+06,4.074252e+08